### ISSUE TITLE
两个小建议

### ISSUE THREAD

**Issue by candyl6** [pkzxs/Aurora.Music#10]
1.RSS订阅增加文件倒序排序功能
2.增加排除文件夹功能，音乐文件夹中有部分不想添加进去

**Comment by pkzxs** [comment]
第一个：请见[add older at top in podcastpage](https://github.com/pkzxs/Aurora.Music/commit/8a60cb41c29f2db107ba1e6f39b221e246f701b9)

第二个：请见[add searching filter](https://github.com/pkzxs/Aurora.Music/commit/95b3f9d6b9e147b0693f05a033ca3d7a8298fffb)
