### ISSUE TITLE
Mojibake

### ISSUE THREAD

**Issue by Copay** [pkzxs/Aurora.Music#11]
## I'm submitting a...

 - Bug report (I searched for similar issues and did not find one) 
 

## Current behavior

Wav文件名,描述,乱码

## Expected behavior

不再乱码?

## Minimal reproduction of the problem with instructions

音乐加入,乱码

## Environment

App Version(s): 

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [x] Spring Creators Update (17133)
- [ ] Insider Build (build number: )

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

![default](https://user-images.githubusercontent.com/11085755/38318135-3d18ca52-3861-11e8-9b85-f578566f54f6.png)

**Comment by pkzxs** [comment]
你好，不知能否上传出问题的 wav 文件，谢谢！

**Comment by Copay** [comment]
https://conya-my.sharepoint.com/:u:/g/personal/corps_mail_fczbl_vip/EQZDKjQxoxFNjtNykdL6Sh4BtGHzzhaQjhZANL71Nsrarg?e=cdJ8Tm

**Comment by pkzxs** [comment]
你好，调试了一下发现是 TagLib 的问题，它读取文件的时候，不经检查直接认为 Tag 里面的文本编码是 utf-8，和这个文件里的编码不匹配就有乱码了。
直接修改 TagLib 比较困难，目前先做了临时的 work around，请见：[Fix wav mojibake](https://github.com/pkzxs/Aurora.Music/commit/d66447d65a994b63e53ae5d465b6442d74e0468f)

**Comment by pkzxs** [comment]
可能还需要重新清除一下应用数据
