### ISSUE TITLE
从小窗口模式返回后异常

### ISSUE THREAD

**Issue by Youxikong** [pkzxs/Aurora.Music#12]
## I'm submitting a...

Bug report

  
 

## Current behavior

从小窗口模式返回后，歌曲信息条显示未在播放，播放进度条仍然在移动，音乐仍然在播放。

## Expected behavior

从小窗口模式返回后，播放控制条一切正常。

## Minimal reproduction of the problem with instructions

1. 播放任意一首音乐
2. 点击播放控制条
3. 点击小窗播放
4. 点击返回

## Environment

```
App Version(s): 

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [x] Spring Creators Update (17133)
- [ ] Insider Build (build number: )

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

```

**Comment by pkzxs** [comment]
请见[Fix blank panel when going back from compact overlay](https://github.com/pkzxs/Aurora.Music/commit/e5565817600f6dd4c06f6bd4989c00b9333faac1)
