### ISSUE TITLE
Wrong Lyrics

### ISSUE THREAD

**Issue by TheLight8** [pkzxs/Aurora.Music#15]
## I'm submitting a...

- Bug report (I searched for similar issues and did not find one)  
 

## Current behavior

Lyrics for wrong song

## Expected behavior

Would be usefull to correct the song.

## Environment

```
App Version(s): 
2.0.55
Windows 10 Build Number:
- [X] Fall Creators Update (16299)
- [ ] Spring Creators Update (17133)
- [ ] Insider Build (build number: )

Device form factor:
- [X] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

```

**Comment by TheLight8** [comment]
Also would be cool to have the possibility to sync lyrics and memorize the sync delay.

**Comment by pkzxs** [comment]
Hi, I'm sorry that wrong lyrics annoyed you. This app provides a very basic lyric searching, all the lyrics are from [gecimi.com](http://gecimi.com/), and actually lyrics on it are out-of-date or mismatched. But we have the ability to add other lyric extensions, so please have a look at [this app](https://www.microsoft.com/store/productId/9P851Q321TD3), which have more lyric sources, may could help you to get the correct lyrics

**Comment by TheLight8** [comment]
Thank you so much, this helped a lot!

**Comment by pkzxs** [comment]
I'll soon add a feature that enables lyric editing, when I'm done, I'll comment below😁

**Comment by TheLight8** [comment]
Thanks, I'm looking forward for this!

**Comment by pkzxs** [comment]
Hi, I've added the lyric editor in Aurora Music, please update to 2.0.62, go to now playing, add click on the edit button on the right top, after my tests, there's still a few bugs in editor, but I want to know your opinion of this editor about is it easy to use? Thanks a lot and have a nice day.

**Comment by TheLight8** [comment]
Beautiful! This worked like magic, it's a little buggy but it really is incredible. One thing I'll modify is the possibility to overwrite the file, also i notice that the "dot" for every line disappear after the first song i modify. Hope this will help!
