### ISSUE TITLE
Large memory usage, does not load scanned albums

### ISSUE THREAD

**Issue by pedrogarcia** [pkzxs/Aurora.Music#17]
## I'm submitting a...

Bug report (I searched for similar issues and did not find one)
 

## Current behavior
App uses close to 1.7GB of ram memory after scan.
List of albums cannot be loaded, even after completely scanning my music folders. 

## Minimal reproduction of the problem with instructions
1. Scan Large Music Library ~= 10.000 songs
2. Click 'albums'

## Environment

```
App Version(s): 

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [x] Spring Creators Update (17133.73)
- [ ] Insider Build (build number: )

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

```

**Comment by pedrogarcia** [comment]
Hi,
Since there are a lot of files, I uploaded them to Onedrive, and I created 2 versions of the zipped folder.
The [first one](https://1drv.ms/u/s!AqM4C-2JYKY1h9xIG56gpupo1NS8nQ), is the full data folder including the  'Artworks' folder. That has about 2GB of files. 
The [second one](https://1drv.ms/u/s!AqM4C-2JYKY1h9xTR8w2LrsXKJLHBQ), is the data folder, but without the 'Artworks' folder. 
Thanks.

**Comment by pedrogarcia** [comment]
@pkzxs If you need the actual music files as well, please email me, I have them on Onedrive, but to avoid possible copyright issues, I am only able to share them via email.

**Comment by pkzxs** [comment]
Hi Pedro Garcia, I've done a bit for performance optimization, please check if this issues is been fixed. If Not, please comment below. We've appreciated for your help.

**Comment by pkzxs** [comment]
all versions greater than 1.0.59
