### ISSUE TITLE
Wav文件 无法显示Album名

### ISSUE THREAD

**Issue by Copay** [pkzxs/Aurora.Music#18]
## I'm submitting a...

 - Bug report (I searched for similar issues and did not find one) 
 

## Current behavior

Wav文件
无法显示Album名 显示Unknown Album 但是编辑标签时可以显示
(另外MP3tag加的封面似乎各种播放器都不识别
## Environment

App Version(s): 

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [x] Spring Creators Update (17133)
- [ ] Insider Build (build number: )

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

![2018-04-15](https://user-images.githubusercontent.com/11085755/38775293-5754f62c-40b1-11e8-9a6c-0d837643216b.png)

**Comment by pkzxs** [comment]
已更正，是个[笔误](https://github.com/pkzxs/Aurora.Music/commit/3a1aba8dfdbb6d76c9573de74415adae87aeeb84#diff-5b37562098746fe290a1ae5e5066cc27L232)
