### ISSUE TITLE
[Feature Request] m3u8 support

### ISSUE THREAD

**Issue by KalilDev** [pkzxs/Aurora.Music#2]
Thanks for the amazing player, tho i cant import my playlists. They are .m3u and i added the folder they are in to the scan, but they didnt appear on the player.

**Comment by pkzxs** [comment]
Thanks for your review! Just as you see, this app doesn't implement the m3u8 feature. But this function is easy to support and I will add it as soon as possible!

**Comment by KalilDev** [comment]
Nice thank you so much!

Em 27 de fev de 2018 05:27, "Xiaosu Zhu" <notifications@github.com>
escreveu:

**Comment by pkzxs** [comment]
I've included commit [301d199](https://github.com/pkzxs/Aurora.Music/commit/301d19931dc9cb163d28cf41fd14eac6b38962be) in the next update, added support for importing .m3u, .m3u8, .zpl, .mpl playlists. Please check it and test bugs! Thank you.

**Comment by KalilDev** [comment]
Nice, thanks so much !!! When the update is avaible i will give feedback and close the issue.
