### ISSUE TITLE
未读取元数据

### ISSUE THREAD

**Issue by OpportunityLiu** [pkzxs/Aurora.Music#20]
## I'm submitting a...

 - Bug report (I searched for similar issues and did not find one)  

## Current behavior

更新新版本后，所有文件的音乐标签无法读取
![image](https://user-images.githubusercontent.com/13471233/38909153-ff56db1a-42f5-11e8-8d31-086250fa14ba.png)

## Environment

```
App Version(s): 
2.0.58
Windows 10 Build Number:
- [x] Fall Creators Update (16299)
- [ ] Spring Creators Update (17133)
- [ ] Insider Build (build number: )

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

```

**Comment by pkzxs** [comment]
奇怪……我试了m4a, mp3, wav 都没问题

![屏幕截图(21).png](https://i.loli.net/2018/04/18/5ad6b39f1f238.png)
![屏幕截图(22).png](https://i.loli.net/2018/04/18/5ad6b3a220b52.png)
![屏幕截图(23).png](https://i.loli.net/2018/04/18/5ad6b3a4e21f1.png)

上次更新是把 taglib 替换成了系统内置的属性读取，因为 taglib 无脑默认 utf-8 编码，导致许多用 gbk 的乱码了。
我怀疑是有多个艺术家，parse 的时候有错

**Comment by pkzxs** [comment]
看了你的图片发现又不是，不知道是怎么回事了

**Comment by OpportunityLiu** [comment]
可能是因为我的文件在OneDrive？貌似OneDrive的文件就是这样

**Comment by OpportunityLiu** [comment]
发现是ICAROS干的
注册了第三方的PropertiesProvider之后这个API就跪了
![image](https://user-images.githubusercontent.com/13471233/38913603-2f02d0e0-430e-11e8-8e95-d033a8c02b0a.png)

**Comment by OpportunityLiu** [comment]
这应该算是Windows的bug了

**Comment by pkzxs** [comment]
OK，不知道有 ICAROS 这么个东西，我去研究研究
