### ISSUE TITLE
页标题显示错误

### ISSUE THREAD

**Issue by OpportunityLiu** [pkzxs/Aurora.Music#21]
## I'm submitting a...

 - Bug report (I searched for similar issues and did not find one)
 

## Current behavior

![image](https://user-images.githubusercontent.com/13471233/38913991-21a36ac0-4310-11e8-8ace-e1a99857de45.png)

## Minimal reproduction of the problem with instructions

1. 打开应用
2. 播放任意歌曲
3. 进入正在播放页
4. 进入设置页

## Environment

```
App Version(s): 2.0.58

Windows 10 Build Number:
- [ x] Fall Creators Update (16299)
- [ ] Spring Creators Update (17133)
- [ ] Insider Build (build number: )

Device form factor:
- [ x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

```

**Comment by pkzxs** [comment]
👌Got it. 代码处理顺序有错

**Comment by pkzxs** [comment]
[这里](https://github.com/pkzxs/Aurora.Music/commit/3987ccf84c783ae16c4952d16e939dcf31588081#diff-f5dc46bd223ea8072c4699eaafad7f59R3169) 修复了黑底黑字的问题

[这里](https://github.com/pkzxs/Aurora.Music/commit/3987ccf84c783ae16c4952d16e939dcf31588081#diff-51c0d7a752085d2c59f3c4957e02cf37R208) 修复了标题错误
