### ISSUE TITLE
Album Art not showing

### ISSUE THREAD

**Issue by GTGOLD** [pkzxs/Aurora.Music#27]
## I'm submitting a...

Bug report (I searched for similar issues and did not find one)

## Current behavior

Some album artwork is not showing in the main library even though it is listed as a cover.jpg in its folder.

## Expected behavior

Album Art showing.

## Minimal reproduction of the problem with instructions

I don't know how to reproduce this error but perhaps the file structure could help:
C:\Users\[user]\Music\Touhou Jazz\Full Albums
C:\Users\[user]\Music\Touhou Jazz\Partial Albums
music is stored in another folder inside the full albums folder as is the album art of the affected songs.
There is also a lot of music this specific structure , around 2000 songs, with several hundred albums each in their own folder. 
## Environment

```
App Version(s): 

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [x ] Spring Creators Update (17133)
- [ ] Insider Build (build number: )

Device form factor:
- [x ] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

```

**Comment by OpportunityLiu** [comment]
Seems covers in file `cover.*` is not supported currently, it should be a feature request.

**Comment by pkzxs** [comment]
Please update to newer version and see if this feature works correctly @GTGOLD , Thx a lot.

**Comment by GTGOLD** [comment]
It does not work for me. Certain albums which have cover.jpg still dont show up in album art. But other albums do show up. I dont think the update fixed it.

**Comment by pkzxs** [comment]
Hi @GTGOLD , I've fixed a few bugs and this seems to work finally. Please upgrade app to 2.0.69 and check if this takes effects. Thank you 😄

**Comment by GTGOLD** [comment]
It works. Thanks!
