### ISSUE TITLE
Add support for metadata of multiple artists

### ISSUE THREAD

**Issue by OpportunityLiu** [pkzxs/Aurora.Music#3]
They are separated by ` / ` (sequence of `space + slash + space`)

![image](https://user-images.githubusercontent.com/13471233/37813177-ec78d3d8-2e9e-11e8-8ef2-0f097a364b96.png)
Meta data shown by system, foobar200, MP3Tag and Groove.
System handles this correctly, Groove ignores artists other than the first one. Other 2 apps doesn't handle this.

**Comment by pkzxs** [comment]
hi, I think it's easy to handle this case, and I'll check for it as soon as possible.
And for dev, could you please share that audio file to me? I can then find how to support it. Thank you!


BTW, do you speak Chinese? If you find it is more convenience, just speak Chinese😁

**Comment by OpportunityLiu** [comment]
[翼をください.zip](https://github.com/pkzxs/Aurora.Music/files/1840732/default.zip)

**Comment by OpportunityLiu** [comment]
我猜并没有任何特殊的地方，真的就只是用 ` / ` 分隔而已

**Comment by pkzxs** [comment]
行，我放到里面一看便知

**Comment by pkzxs** [comment]
确实是用了一个 / 来分割，那我就直接把 / 当作分隔符好了

**Comment by OpportunityLiu** [comment]
两边有空格的，单独的/不是分隔符，不然歌手名称就不能有/了不是

**Comment by pkzxs** [comment]
嗯，这个我肯定要考虑的，等我周末写一下

**Comment by OpportunityLiu** [comment]
![image](https://user-images.githubusercontent.com/13471233/37820263-08e41cf0-2ebb-11e8-9990-fc056e7508c6.png)
![image](https://user-images.githubusercontent.com/13471233/37820303-23b2cba8-2ebb-11e8-883e-e5d9d1cc3d0e.png)

看来空格并不重要，M$真的认为歌手名字有 `/` 就是活该

**Comment by pkzxs** [comment]
这也太粗糙了🤣

**Comment by OpportunityLiu** [comment]
![image](https://user-images.githubusercontent.com/13471233/37820813-c35a83e8-2ebc-11e8-8aa3-c151ff5128a0.png)
又试了一下，看来公认的是多条记录

**Comment by pkzxs** [comment]
我觉得只有资源浏览器里是自动按 `/` 分割的，foobar 和 MP3tag 都是原样显示

**Comment by OpportunityLiu** [comment]
# 多条记录是正确的
![image](https://user-images.githubusercontent.com/13471233/37821645-2a1eef7c-2ebf-11e8-9af9-e3cbd0ccb688.png)
Foobar，注意左栏，还有列表视图和详细信息不同，说明理解了多条记录
![image](https://user-images.githubusercontent.com/13471233/37821696-49c56ef0-2ebf-11e8-84d2-48aacd235e39.png)
Mp3Tag,详细视图分为多条记录，编辑框和列表显示为`\\`分隔
![image](https://user-images.githubusercontent.com/13471233/37821731-646ebdd8-2ebf-11e8-9a01-0d35491d878e.png)
系统属性，正确支持
![image](https://user-images.githubusercontent.com/13471233/37821757-7216cbce-2ebf-11e8-8f5a-ca222d47dcde.png)
![image](https://user-images.githubusercontent.com/13471233/37821773-7cf55f6a-2ebf-11e8-986a-b6e0896ea433.png)
最后本软件其实也是理解这种做法的，可惜艺术家没分开

**Comment by pkzxs** [comment]
嗯，这首歌的 tag 的歌手里面，是写入了多条记录的。

我的软件用的 tag 读取库是 `TagLib.sharp`, 它读取 tag 的时候，歌手就是一个数组，前面那个 `翼をください` 的歌手数组只有一个元素，用 ` / ` 分割了，而 `Beauty as the beast` 这首歌，歌手数组有多个元素，我的软件已经处理了这种情况，艺术家显示的时候用 `，` 排列，编辑标签的对话框里则是用的 `;`。

所以目前的问题是：
1. tag 里面歌手只有一行，还用了 ` / ` 分开，把它当成多个歌手就好了；
2. tag 里面歌手有多个，要把他们分开，比如 `歌曲a` 由 `歌手a` `歌手b` 演唱，要既能在 `歌手a` 的页面看见 `歌曲a`，也能在 `歌手b` 的页面看见 `歌曲a`

对吗？

**Comment by OpportunityLiu** [comment]
![image](https://user-images.githubusercontent.com/13471233/37823302-11ca29c8-2ec4-11e8-8ba7-41d37f68aed2.png)
实际的分隔符是`\0`
http://id3.org/id3v2.4.0-structure

**Comment by OpportunityLiu** [comment]
主要还是 2，1的话是M$自己整的幺蛾子，支持了的话可能真的有名字里有 `\` 的艺术家莫名中枪

**Comment by pkzxs** [comment]
妥👌

**Comment by pkzxs** [comment]
刚才提交了[一次](https://github.com/pkzxs/Aurora.Music/commit/2eb1fe1761a8229a1123dace1a4ee8ca25dd8a57)

我找几个文件测试一下，要是没问题就更新了

**Comment by OpportunityLiu** [comment]
![image](https://user-images.githubusercontent.com/13471233/37864029-a193c368-2fa3-11e8-89b3-3588872848c4.png)
独唱曲目和合唱曲目被分开了


![image](https://user-images.githubusercontent.com/13471233/37864057-1e03ff26-2fa4-11e8-8078-132ef12a10dd.png)
![image](https://user-images.githubusercontent.com/13471233/37864059-2cdbb692-2fa4-11e8-8e98-643ffd238e55.png)
还有，在没有指定专辑艺术家的情况下，默认的专辑艺术家自动拥有了整张专辑

**Comment by pkzxs** [comment]
啊，了解了。这个解决起来不太好办，可能还得把专辑的存储方法作调整，我还是要到周末有空了才能改改。最近有些忙😥

**Comment by pkzxs** [comment]
星期天的更新初步解决了一些问题，你看看有没有其他问题。专辑的信息可能要重新更新一下才能有效果，就是加几首歌到文件夹里面，让应用触发刷新数据库的操作

**Comment by OpportunityLiu** [comment]
![image](https://user-images.githubusercontent.com/13471233/38224671-ab455cf0-3723-11e8-922c-5cb739b51f26.png)
显示多个歌手的问题还在，不过同一个歌手点进去的曲目列表都是全的。

第二个问题倒是解决了
![image](https://user-images.githubusercontent.com/13471233/38224806-3ca6dfc0-3724-11e8-9c3f-d852b3dde2ac.png)

**Comment by OpportunityLiu** [comment]
![image](https://user-images.githubusercontent.com/13471233/38452169-22e3155e-3a71-11e8-8ca7-73e08a697da0.png)
专辑艺术家名字重复

![image](https://user-images.githubusercontent.com/13471233/38452173-3d9d2484-3a71-11e8-9b42-94d1356cb948.png)
![image](https://user-images.githubusercontent.com/13471233/38452174-44991ce8-3a71-11e8-9f44-3e87d269d231.png)
没有参与的专辑显示在了艺术家的页面下，用的字符串匹配？

**Comment by OpportunityLiu** [comment]
而且你的 `SQLEscaping(string)` 也有问题吧

![image](https://user-images.githubusercontent.com/13471233/38454005-9e1b8c40-3a91-11e8-972f-a8abb3c11b6d.png)

**Comment by pkzxs** [comment]
分隔符我用的是$|$，这样应该就是 `"SELECT * FROM ALBUM WHERE ALBUMARTISTS LIKE '{value}$|$%' OR ALBUMARTISTS LIKE '%$|${value}$|$%' OR ALBUMARTISTS LIKE '%$|${value}' OR ALBUMARTISTS = '{value}' "`
估计行

那个`SQLEscaping(string)`我是乱写的，我曾经搜索过 没找到，看它工作没问题 就放那没动了，我试试你这个

**Comment by OpportunityLiu** [comment]
我其实更好奇的是为啥不用EF，自己写SQL太酸爽了

**Comment by OpportunityLiu** [comment]
=操作应该是 `value.Replace("'","''")`
LIKE 操作应该是 `value.Replace("'","''").Replace("[","[[]").Replace("%","[%]").Replace("_","[_]")`

所以最后一个还是直接写 `ALBUMARTISTS LIKE '{value}'` 方便点

**Comment by pkzxs** [comment]
开始写的时候我不知道有EF……，然后用了 SQLite-net，而且数据库部分也是很早就写完了，也没有动力去改了……，可能某个惬意的午后会重写一下😂

**Comment by OpportunityLiu** [comment]
这个Feature现在运行良好，应该没什么问题了

**Comment by OpportunityLiu** [comment]
![image](https://user-images.githubusercontent.com/13471233/38986693-c0d7b4b2-43ff-11e8-9148-a5c283891f01.png)
不对啊，这问题还在？
