### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by touseefbsb** [pkzxs/Aurora.Music#41]
Failed to Build with Following errors : 

![image](https://user-images.githubusercontent.com/11542189/44746363-982b9c00-ab23-11e8-812d-cbd6e2e88ded.png)

one of the errors is : 

'C:\Users\fcuv3\Source\Repos\Aurora.Music\Source\Aurora.Shared\bin\x64\Debug\Aurora.Shared.dll' could not be found	'TagLib.Sharp'

**Comment by OpportunityLiu** [comment]
https://github.com/pkzxs/Aurora.Music/blob/3de808093f727abf844d1491ed2d311e55abf166/.gitignore#L262-L263

Some files are not included in the source control.

**Comment by touseefbsb** [comment]
after commenting those 2 lines, I am still getting 11 errors. 
![image](https://user-images.githubusercontent.com/11542189/44992916-2683a000-afb2-11e8-9990-642a865741f9.png)

**Comment by OpportunityLiu** [comment]
READ error messages, do not COUNT THEM

**Comment by touseefbsb** [comment]
@OpportunityLiu  if I understood the errors I would not have opened this issue :) the sole reason I opened the issue is because I have no idea what is the reason of these errors, so I posted the screen shot of the errors, if they are unreadable please let me know I will copy and paste them as well. Thanks.

**Comment by touseefbsb** [comment]
from wht I can see is that there are some files excluded which limits the features, wht I dont know is how to disable all other features which are causing the error? where can I comment out the code for the remaining error causing features? the error window is mentioning the missing files but it is not mentioning obviously that where the code of those files is being used, for that I need some help.

**Comment by OpportunityLiu** [comment]
After comment out these lines, just remove missed files from solution explorer

**Comment by touseefbsb** [comment]
I removed all the files with yellow exclamation indicator ( missing files ) and then also removed the missing .net standard 2.0.2 references from the projects, but errors are exactly the same then I noticed that within shared project there are 2 more missing references , I tried removing them adding them again because I know they will be required, but the yellow missing reference on them is not going away. here s the screenshot for that. 
![image](https://user-images.githubusercontent.com/11542189/45035956-ac681f80-b074-11e8-985c-a09198719e44.png)

**Comment by OpportunityLiu** [comment]
Have you installed this?
![image](https://user-images.githubusercontent.com/13471233/45161888-5be0f580-b21f-11e8-9313-02d4ff03be87.png)

And show me the output window as the error list does not show the order of these errors.

**Comment by touseefbsb** [comment]
yes I double checked the sqlite extension was already installed.

**Comment by touseefbsb** [comment]
and here is the output window of "Build"

`Error occurred while restoring NuGet packages: The operation failed as details for project LrcParser could not be loaded.
1>------ Build started: Project: Aurora.Shared, Configuration: Debug Any CPU ------
2>------ Build started: Project: LrcParser, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2377,5): error MSB3779: The processor architecture of the project being built "Any CPU" is not supported by the referenced SDK "Microsoft.VCLibs.Desktop, Version=14.0". Please consider changing the targeted processor architecture of your project (in Visual Studio this can be done through the Configuration Manager) to one of the architectures supported by the SDK: "x86, x64".
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2377,5): error MSB3779: The processor architecture of the project being built "Any CPU" is not supported by the referenced SDK "SQLite.UWP.2015, Version=3.24.0". Please consider changing the targeted processor architecture of your project (in Visual Studio this can be done through the Configuration Manager) to one of the architectures supported by the SDK: "x86, x64, ARM".
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2377,5): warning MSB3781: The SDK "SQLite.UWP.2015, Version=3.24.0" depends on the following SDK(s) "Microsoft.VCLibs, version=14.0", which have not been added to the project or were not found. Please ensure that you add these dependencies to your project or you may experience runtime issues. You can add dependencies to your project through the Reference Manager.
3>------ Build started: Project: TagLib.Sharp, Configuration: Debug Any CPU ------
3>CSC : error CS0006: Metadata file 'C:\Users\fcuv3\Source\Repos\Aurora.Music\Source\Aurora.Shared\bin\Debug\Aurora.Shared.dll' could not be found
4>------ Build started: Project: ExpressionBuilder, Configuration: Debug Any CPU ------
4>  ExpressionBuilder -> C:\Users\fcuv3\Source\Repos\Aurora.Music\Source\ExpressionBuilder\bin\Debug\ExpressionBuilder.dll
5>------ Build started: Project: StarButton, Configuration: Debug Any CPU ------
2>LrcParser -> C:\Users\fcuv3\Source\Repos\Aurora.Music\Source\LrcParser\bin\Debug\netstandard2.0\LrcParser.dll
6>------ Build started: Project: Aurora.Music.Core, Configuration: Debug Any CPU ------
5>  StarButton -> C:\Users\fcuv3\Source\Repos\Aurora.Music\Source\StarButton\bin\Debug\StarButton.dll
6>CSC : error CS0006: Metadata file 'C:\Users\fcuv3\Source\Repos\Aurora.Music\Source\Aurora.Shared\bin\Debug\Aurora.Shared.dll' could not be found
6>CSC : error CS0006: Metadata file 'C:\Users\fcuv3\Source\Repos\Aurora.Music\Source\TagLib.Sharp\bin\Debug\TagLib.Sharp.dll' could not be found
7>------ Build started: Project: Aurora.Music.Effects, Configuration: Debug Any CPU ------
8>------ Build started: Project: Aurora.Music.Services, Configuration: Debug Any CPU ------
7>CSC : error CS0006: Metadata file 'C:\Users\fcuv3\Source\Repos\Aurora.Music\Source\Aurora.Music.Core\bin\Debug\Aurora.Music.Core.dll' could not be found
9>------ Build started: Project: Aurora.Music.PlaybackEngine, Configuration: Debug Any CPU ------
8>CSC : error CS0006: Metadata file 'C:\Users\fcuv3\Source\Repos\Aurora.Music\Source\Aurora.Music.Core\bin\Debug\Aurora.Music.Core.dll' could not be found
8>CSC : error CS0006: Metadata file 'C:\Users\fcuv3\Source\Repos\Aurora.Music\Source\Aurora.Shared\bin\Debug\Aurora.Shared.dll' could not be found
9>CSC : error CS0006: Metadata file 'C:\Users\fcuv3\Source\Repos\Aurora.Music\Source\Aurora.Music.Core\bin\Debug\Aurora.Music.Core.dll' could not be found
9>CSC : error CS0006: Metadata file 'C:\Users\fcuv3\Source\Repos\Aurora.Music\Source\Aurora.Music.Effects\bin\Debug\Aurora.Music.Effects.winmd' could not be found
9>CSC : error CS0006: Metadata file 'C:\Users\fcuv3\Source\Repos\Aurora.Music\Source\Aurora.Shared\bin\Debug\Aurora.Shared.dll' could not be found
9>CSC : error CS0006: Metadata file 'C:\Users\fcuv3\Source\Repos\Aurora.Music\Source\TagLib.Sharp\bin\Debug\TagLib.Sharp.dll' could not be found
10>------ Skipped Build: Project: Aurora.Music, Configuration: Debug x86 ------
10>Project not selected to build for this solution configuration 
11>------ Skipped Deploy: Project: Aurora.Music, Configuration: Debug x86 ------
11>Project not selected to build for this solution configuration 
========== Build: 3 succeeded, 6 failed, 0 up-to-date, 1 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 1 skipped ==========`

**Comment by touseefbsb** [comment]
yes selecting a specific architecture solved the issue
