### ISSUE TITLE
拖放无封面的文件时动画不播放

### ISSUE THREAD

**Issue by OpportunityLiu** [pkzxs/Aurora.Music#8]
![image](https://user-images.githubusercontent.com/13471233/38185486-db71733a-3680-11e8-875f-c2d65cd0f315.png)

1. 当无封面图片时 `Image_ImageOpened` 后 `Artwork_ImageOpened` 事件不发生
2. 拖放第二个无封面图片的文件时不会再次触发 `Image_ImageOpened`

**Comment by pkzxs** [comment]
请见 [fix drop animation of none artwork](https://github.com/pkzxs/Aurora.Music/commit/340225eb7d52d9f971cc01a415677509e0373dd1)
